# docker-compose.yml

version: "3.9"

services:
  db:
    image: postgres:15.1-alpine
    container_name: postgres
    restart: on-failure
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    ports:
     - "${POSTGRES_PORT}:${POSTGRES_PORT}"
#    volumes:
#      - ./data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: cache
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "cache-cli", "ping" ]
      interval: 5s
      timeout: 10s
      retries: 10

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi
    # image: fast-api:latest
    restart: on-failure
    environment:
      POSTGRES_HOST: "db"
      POSTGRES_PORT: "${POSTGRES_PORT}"
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000


networks:
  default:
      name: lan_fastapi
