FROM python:3.10-slim as test

#
WORKDIR /app

#
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONBUFFERED 1

#
COPY . .

#
RUN pip install --no-cache-dir --upgrade -r /app/requirements.txt

#
CMD ["pytest", "-v"]